Update github-actions-demo.yml

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -106,13 +106,25 @@ jobs:
             -d "grant_type=client_credentials")
           access_token=$(echo "$response" | jq -r '.access_token')
           echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV
-      
+          echo "Response from token endpoint: $response"
+          access_token=$(echo "$response" | jq -r '.access_token')
+          if [ -z "$access_token" ] || [ "$access_token" == "null" ]; then
+              echo "Access token not found. Response was: $response"
+              exit 1
+          fi
+          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV
+
+      - name:  Verify Access Token Format
+        run: |
+          if [[ "$ACCESS_TOKEN" != *.*.* ]]; then
+            echo "Error: ACCESS_TOKEN is not in JWT format."
+            exit 1
+          fi
+          
       - name: Create keycloak Client
         env:
           ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
-          ACTIONS_STEP_DEBUG: true
         run: |
-          echo "::debug::ACCESS_TOKEN=$ACCESS_TOKEN"
           curl -s -X POST "https://dev.auth.mlops.ingka.com/admin/realms/istio/clients" \
           -H 'Content-Type: application/json' \
           -H 'Authorization: Bearer $ACCESS_TOKEN' \
